
version: 2
jobs:
  build:
    working_directory: ~/test-ansible-app
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - restore_cache:
         key:  checksum "package.json" 
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key:  checksum "package.json" 
          paths:
           - node_modules
      - run:
          name: Build the application
          command: npm run build
      - persist_to_workspace:
          root: ~/test-ansible-app
          paths:
            - package.json
            - node_modules
            - src
            - build

      
workflows:
  version: 2
  build-test-app:
    jobs:
      - build
      