
version: 2
jobs:
  build:
    working_directory: ~/test-ansible-app
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - restore_cache:
         key:  cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key:  cache-{{ checksum "package.json" }}
          paths:
           - node_modules
      - run:
          name: Build the application
          command: npm run build
      - persist_to_workspace:
          root: ~/test-ansible-app
          paths:
            - package.json
            - node_modules
            - src
            - build
  deploy:
    docker:
      - image: cimg/aws:2023.08
    steps:
      - checkout
      - attach_workspace:
          at: ~/test-ansible-app
      - run: aws --version
          environment:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      - run: aws s3 sync build/ s3://circleci-app-dev-s3-us-east-1
    
    
workflows:
  version: 2
  build-test-app:
    jobs:
      - build
      - deploy:
            requires:
            - build
      