
version: 2
jobs:
  build:
    working_directory: ~/test-ansible-app
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - restore_cache:
         key:  cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key:  cache-{{ checksum "package.json" }}
          paths:
           - node_modules
      - run:
          name: Build the application
          command: npm run build
      - persist_to_workspace:
          root: ~/test-ansible-app
          paths:
            - package.json
            - node_modules
            - src
            - build
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - attach_workspace:
          at: ~/test-ansible-app
      - run:
          #Get all pre-requisites
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              awscli==1.14.37
            # # Login to ecr and docker login
            # aws_login=`aws ecr get-login --no-include-email --region eu-west-1`
            # eval $aws_login
            # aws s3 sync build/ s3://test-another-app
      - run: aws --version
      # - run:
      #     name: Process template file
      #     environment:
      #       AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      #       AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      # - run: aws s3 sync build/ s3://circleci-app-dev-s3-us-east-1
    
    
workflows:
  version: 2
  build-test-app:
    jobs:
      - build
      - deploy:
            requires:
            - build
      